export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const FETCH_ME_SUCCESS = "FETCH_ME_SUCCESS";
export const FETCH_ME_FAIL = "FETCH_ME_FAIL";
export const SET_OWN_USER_READY = "SET_OWN_USER_READY";

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL";
export const SET_ONLINE_USERS = "SET_ONLINE_USERS";

export const ADD_TYPING_USER = "ADD_TYPING_USER";
export const REMOVE_TYPING_USER = "REMOVE_TYPING_USER";

export const FETCH_CONTACT_USERS_SUCCESS = "FETCH_CONTACT_USERS_SUCCESS";
export const FETCH_CONTACT_USERS_FAIL = "FETCH_CONTACT_USERS_FAIL";

export const SET_LOGIN_REG_MESSAGE = "SET_LOGIN_REG_MESSAGE";

export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAIL = "CREATE_CHAT_FAIL";

export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const GET_CHATS_FAIL = "GET_CHATS_FAIL";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";
export const SET_MESSAGE_READY = "SET_MESSAGE_READY";
export const ADD_MESSAGE_FROM_SOCKET = "ADD_MESSAGE_FROM_SOCKET";

export const SET_NEW_MESSAGE_NOTIF = "SET_NEW_MESSAGE_NOTIF";
export const ADD_NEW_MESSAGE_NOTIF = "ADD_NEW_MESSAGE_NOTIF";
export const REMOVE_NEW_MESSAGE_NOTIF = "REMOVE_NEW_MESSAGE_NOTIF";

export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
export const SET_CHATS_READY = "SET_CHATS_READY";

export const ADD_PENDING_MESSAGE = "ADD_PENDING_MESSAGE";
export const SET_PENDING_MESSAGE = "SET_PENDING_MESSAGE";